### ISSUE TITLE
Move parameters into JSON

### ISSUE THREAD

**Issue by ericvaandering** [kenbloom/resource-modeling#1]
There are a few numbers that I'd suggest moving into a config file rather than in the code.

**Comment by kenbloom** [comment]
Sounds great!  You are right, it would be cleaner that way.  Can you show me an example for how it is done?

**Comment by ericvaandering** [comment]
Yeah, let me whip up a PR to do this. I'll start a master config that can share parameters between cpu.py and diskspace.py (and network.py?)

**Comment by ericvaandering** [comment]
Fixed by #3. Should have closed automatically.
