### ISSUE TITLE
Better histogramming tools

### ISSUE THREAD

**Issue by kenbloom** [kenbloom/resource-modeling#8]
I successfully made a histogram in cpu.py, but it was a real pain in the neck!  matplotlib doesn't work the way I think of it.  @bbockelman, what would DIANA suggest that I use to make a histogram?

**Comment by ericvaandering** [comment]
You aren't really plotting a histogram but a plain bar chart: https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html

I think you forced your bar chart data into a format you could histogram.

**Comment by kenbloom** [comment]
In fact I started by making a bar chart.  But that required me to do a weird transform on the data such that I lost the clear coupling between the y values and the year number.  So I forced into a histogram instead, with the proper binning.  OK, perhaps what I really want is better graphing tools.

**Comment by ericvaandering** [comment]
Close this?

**Comment by kenbloom** [comment]
I suppose.  I'm still finding this to be a pain but we are finding ways.
